name: finalmobile
description: "A Flutter project with API consumption and SQLite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  provider: ^6.1.1
  path: ^1.8.3
  sqflite_common_ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true